# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compas_timber_pb/data/proto/plate.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'compas_timber_pb/data/proto/plate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from compas_pb.data.proto import polyline_pb2 as compas__pb_dot_data_dot_proto_dot_polyline__pb2
from compas_pb.data.proto import vector_pb2 as compas__pb_dot_data_dot_proto_dot_vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'compas_timber_pb/data/proto/plate.proto\x12\x0e\x63ompas_pb.data\x1a#compas_pb/data/proto/polyline.proto\x1a!compas_pb/data/proto/vector.proto\"\x95\x01\n\tPlateData\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12-\n\x07outline\x18\x03 \x01(\x0b\x32\x1c.compas_pb.data.PolylineData\x12\x11\n\tthickness\x18\x04 \x01(\x02\x12*\n\x06vector\x18\x05 \x01(\x0b\x32\x1a.compas_pb.data.VectorDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compas_timber_pb.data.proto.plate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLATEDATA']._serialized_start=132
  _globals['_PLATEDATA']._serialized_end=281
# @@protoc_insertion_point(module_scope)
