// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: compas_pb/data/proto/message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CompasPb.Data {

  /// <summary>Holder for reflection information generated from compas_pb/data/proto/message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for compas_pb/data/proto/message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJjb21wYXNfcGIvZGF0YS9wcm90by9tZXNzYWdlLnByb3RvEg5jb21wYXNf",
            "cGIuZGF0YRogY29tcGFzX3BiL2RhdGEvcHJvdG8vcG9pbnQucHJvdG8aIWNv",
            "bXBhc19wYi9kYXRhL3Byb3RvL3ZlY3Rvci5wcm90bxofY29tcGFzX3BiL2Rh",
            "dGEvcHJvdG8vbGluZS5wcm90bxoiY29tcGFzX3BiL2RhdGEvcHJvdG8vZWxl",
            "bWVudC5wcm90bxogY29tcGFzX3BiL2RhdGEvcHJvdG8vZnJhbWUucHJvdG8i",
            "rAMKB0FueURhdGESJgoEdHlwZRgBIAEoDjIYLmNvbXBhc19wYi5kYXRhLkRh",
            "dGFUeXBlEioKBXBvaW50GAIgASgLMhkuY29tcGFzX3BiLmRhdGEuUG9pbnRE",
            "YXRhSAASLAoGdmVjdG9yGAMgASgLMhouY29tcGFzX3BiLmRhdGEuVmVjdG9y",
            "RGF0YUgAEigKBGxpbmUYBCABKAsyGC5jb21wYXNfcGIuZGF0YS5MaW5lRGF0",
            "YUgAEioKBWZyYW1lGAUgASgLMhkuY29tcGFzX3BiLmRhdGEuRnJhbWVEYXRh",
            "SAASLgoHZWxlbWVudBgGIAEoCzIbLmNvbXBhc19wYi5kYXRhLkVsZW1lbnRE",
            "YXRhSAASKAoEbGlzdBgHIAEoCzIYLmNvbXBhc19wYi5kYXRhLkxpc3REYXRh",
            "SAASKAoEZGljdBgIIAEoCzIYLmNvbXBhc19wYi5kYXRhLkRpY3REYXRhSAAS",
            "DQoDaW50GAkgASgFSAASDwoFZmxvYXQYCiABKAJIABIOCgRib29sGAsgASgI",
            "SAASDQoDc3RyGAwgASgJSABCBgoEZGF0YSIxCghMaXN0RGF0YRIlCgRkYXRh",
            "GAEgAygLMhcuY29tcGFzX3BiLmRhdGEuQW55RGF0YSKCAQoIRGljdERhdGES",
            "MAoEZGF0YRgBIAMoCzIiLmNvbXBhc19wYi5kYXRhLkRpY3REYXRhLkRhdGFF",
            "bnRyeRpECglEYXRhRW50cnkSCwoDa2V5GAEgASgJEiYKBXZhbHVlGAIgASgL",
            "MhcuY29tcGFzX3BiLmRhdGEuQW55RGF0YToCOAEiNAoLTWVzc2FnZURhdGES",
            "JQoEZGF0YRgBIAEoCzIXLmNvbXBhc19wYi5kYXRhLkFueURhdGEqiwEKCERh",
            "dGFUeXBlEgsKB1VOS05PV04QABIJCgVQT0lOVBABEgoKBlZFQ1RPUhACEggK",
            "BExJTkUQAxIJCgVGUkFNRRAEEgsKB0VMRU1FTlQQBRIICgRMSVNUEAYSCAoE",
            "RElDVBAHEgcKA0lOVBAIEgkKBUZMT0FUEAkSCAoEQk9PTBAKEgcKA1NUUhAL",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CompasPb.Data.PointReflection.Descriptor, global::CompasPb.Data.VectorReflection.Descriptor, global::CompasPb.Data.LineReflection.Descriptor, global::CompasPb.Data.ElementReflection.Descriptor, global::CompasPb.Data.FrameReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CompasPb.Data.DataType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CompasPb.Data.AnyData), global::CompasPb.Data.AnyData.Parser, new[]{ "Type", "Point", "Vector", "Line", "Frame", "Element", "List", "Dict", "Int", "Float", "Bool", "Str" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CompasPb.Data.ListData), global::CompasPb.Data.ListData.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CompasPb.Data.DictData), global::CompasPb.Data.DictData.Parser, new[]{ "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::CompasPb.Data.MessageData), global::CompasPb.Data.MessageData.Parser, new[]{ "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// A message to hold any data type 
  /// </summary>
  public enum DataType {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("POINT")] Point = 1,
    [pbr::OriginalName("VECTOR")] Vector = 2,
    [pbr::OriginalName("LINE")] Line = 3,
    [pbr::OriginalName("FRAME")] Frame = 4,
    [pbr::OriginalName("ELEMENT")] Element = 5,
    [pbr::OriginalName("LIST")] List = 6,
    [pbr::OriginalName("DICT")] Dict = 7,
    [pbr::OriginalName("INT")] Int = 8,
    [pbr::OriginalName("FLOAT")] Float = 9,
    [pbr::OriginalName("BOOL")] Bool = 10,
    [pbr::OriginalName("STR")] Str = 11,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnyData : pb::IMessage<AnyData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnyData> _parser = new pb::MessageParser<AnyData>(() => new AnyData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnyData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CompasPb.Data.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnyData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnyData(AnyData other) : this() {
      type_ = other.type_;
      switch (other.DataCase) {
        case DataOneofCase.Point:
          Point = other.Point.Clone();
          break;
        case DataOneofCase.Vector:
          Vector = other.Vector.Clone();
          break;
        case DataOneofCase.Line:
          Line = other.Line.Clone();
          break;
        case DataOneofCase.Frame:
          Frame = other.Frame.Clone();
          break;
        case DataOneofCase.Element:
          Element = other.Element.Clone();
          break;
        case DataOneofCase.List:
          List = other.List.Clone();
          break;
        case DataOneofCase.Dict:
          Dict = other.Dict.Clone();
          break;
        case DataOneofCase.Int:
          Int = other.Int;
          break;
        case DataOneofCase.Float:
          Float = other.Float;
          break;
        case DataOneofCase.Bool:
          Bool = other.Bool;
          break;
        case DataOneofCase.Str:
          Str = other.Str;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnyData Clone() {
      return new AnyData(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::CompasPb.Data.DataType type_ = global::CompasPb.Data.DataType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.DataType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 2;
    /// <summary>
    /// a meesage to hold COMPAS obejct data types 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.PointData Point {
      get { return dataCase_ == DataOneofCase.Point ? (global::CompasPb.Data.PointData) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Point;
      }
    }

    /// <summary>Field number for the "vector" field.</summary>
    public const int VectorFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.VectorData Vector {
      get { return dataCase_ == DataOneofCase.Vector ? (global::CompasPb.Data.VectorData) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Vector;
      }
    }

    /// <summary>Field number for the "line" field.</summary>
    public const int LineFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.LineData Line {
      get { return dataCase_ == DataOneofCase.Line ? (global::CompasPb.Data.LineData) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Line;
      }
    }

    /// <summary>Field number for the "frame" field.</summary>
    public const int FrameFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.FrameData Frame {
      get { return dataCase_ == DataOneofCase.Frame ? (global::CompasPb.Data.FrameData) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Frame;
      }
    }

    /// <summary>Field number for the "element" field.</summary>
    public const int ElementFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.ElementData Element {
      get { return dataCase_ == DataOneofCase.Element ? (global::CompasPb.Data.ElementData) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Element;
      }
    }

    /// <summary>Field number for the "list" field.</summary>
    public const int ListFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.ListData List {
      get { return dataCase_ == DataOneofCase.List ? (global::CompasPb.Data.ListData) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.List;
      }
    }

    /// <summary>Field number for the "dict" field.</summary>
    public const int DictFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.DictData Dict {
      get { return dataCase_ == DataOneofCase.Dict ? (global::CompasPb.Data.DictData) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Dict;
      }
    }

    /// <summary>Field number for the "int" field.</summary>
    public const int IntFieldNumber = 9;
    /// <summary>
    /// a meesage to hold built-in data types 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Int {
      get { return HasInt ? (int) data_ : 0; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Int;
      }
    }
    /// <summary>Gets whether the "int" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInt {
      get { return dataCase_ == DataOneofCase.Int; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "int" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInt() {
      if (HasInt) {
        ClearData();
      }
    }

    /// <summary>Field number for the "float" field.</summary>
    public const int FloatFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Float {
      get { return HasFloat ? (float) data_ : 0F; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Float;
      }
    }
    /// <summary>Gets whether the "float" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFloat {
      get { return dataCase_ == DataOneofCase.Float; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "float" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFloat() {
      if (HasFloat) {
        ClearData();
      }
    }

    /// <summary>Field number for the "bool" field.</summary>
    public const int BoolFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Bool {
      get { return HasBool ? (bool) data_ : false; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Bool;
      }
    }
    /// <summary>Gets whether the "bool" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBool {
      get { return dataCase_ == DataOneofCase.Bool; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "bool" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBool() {
      if (HasBool) {
        ClearData();
      }
    }

    /// <summary>Field number for the "str" field.</summary>
    public const int StrFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Str {
      get { return HasStr ? (string) data_ : ""; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.Str;
      }
    }
    /// <summary>Gets whether the "str" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStr {
      get { return dataCase_ == DataOneofCase.Str; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "str" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStr() {
      if (HasStr) {
        ClearData();
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Point = 2,
      Vector = 3,
      Line = 4,
      Frame = 5,
      Element = 6,
      List = 7,
      Dict = 8,
      Int = 9,
      Float = 10,
      Bool = 11,
      Str = 12,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnyData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnyData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Point, other.Point)) return false;
      if (!object.Equals(Vector, other.Vector)) return false;
      if (!object.Equals(Line, other.Line)) return false;
      if (!object.Equals(Frame, other.Frame)) return false;
      if (!object.Equals(Element, other.Element)) return false;
      if (!object.Equals(List, other.List)) return false;
      if (!object.Equals(Dict, other.Dict)) return false;
      if (Int != other.Int) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Float, other.Float)) return false;
      if (Bool != other.Bool) return false;
      if (Str != other.Str) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::CompasPb.Data.DataType.Unknown) hash ^= Type.GetHashCode();
      if (dataCase_ == DataOneofCase.Point) hash ^= Point.GetHashCode();
      if (dataCase_ == DataOneofCase.Vector) hash ^= Vector.GetHashCode();
      if (dataCase_ == DataOneofCase.Line) hash ^= Line.GetHashCode();
      if (dataCase_ == DataOneofCase.Frame) hash ^= Frame.GetHashCode();
      if (dataCase_ == DataOneofCase.Element) hash ^= Element.GetHashCode();
      if (dataCase_ == DataOneofCase.List) hash ^= List.GetHashCode();
      if (dataCase_ == DataOneofCase.Dict) hash ^= Dict.GetHashCode();
      if (HasInt) hash ^= Int.GetHashCode();
      if (HasFloat) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Float);
      if (HasBool) hash ^= Bool.GetHashCode();
      if (HasStr) hash ^= Str.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::CompasPb.Data.DataType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Point) {
        output.WriteRawTag(18);
        output.WriteMessage(Point);
      }
      if (dataCase_ == DataOneofCase.Vector) {
        output.WriteRawTag(26);
        output.WriteMessage(Vector);
      }
      if (dataCase_ == DataOneofCase.Line) {
        output.WriteRawTag(34);
        output.WriteMessage(Line);
      }
      if (dataCase_ == DataOneofCase.Frame) {
        output.WriteRawTag(42);
        output.WriteMessage(Frame);
      }
      if (dataCase_ == DataOneofCase.Element) {
        output.WriteRawTag(50);
        output.WriteMessage(Element);
      }
      if (dataCase_ == DataOneofCase.List) {
        output.WriteRawTag(58);
        output.WriteMessage(List);
      }
      if (dataCase_ == DataOneofCase.Dict) {
        output.WriteRawTag(66);
        output.WriteMessage(Dict);
      }
      if (HasInt) {
        output.WriteRawTag(72);
        output.WriteInt32(Int);
      }
      if (HasFloat) {
        output.WriteRawTag(85);
        output.WriteFloat(Float);
      }
      if (HasBool) {
        output.WriteRawTag(88);
        output.WriteBool(Bool);
      }
      if (HasStr) {
        output.WriteRawTag(98);
        output.WriteString(Str);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::CompasPb.Data.DataType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Point) {
        output.WriteRawTag(18);
        output.WriteMessage(Point);
      }
      if (dataCase_ == DataOneofCase.Vector) {
        output.WriteRawTag(26);
        output.WriteMessage(Vector);
      }
      if (dataCase_ == DataOneofCase.Line) {
        output.WriteRawTag(34);
        output.WriteMessage(Line);
      }
      if (dataCase_ == DataOneofCase.Frame) {
        output.WriteRawTag(42);
        output.WriteMessage(Frame);
      }
      if (dataCase_ == DataOneofCase.Element) {
        output.WriteRawTag(50);
        output.WriteMessage(Element);
      }
      if (dataCase_ == DataOneofCase.List) {
        output.WriteRawTag(58);
        output.WriteMessage(List);
      }
      if (dataCase_ == DataOneofCase.Dict) {
        output.WriteRawTag(66);
        output.WriteMessage(Dict);
      }
      if (HasInt) {
        output.WriteRawTag(72);
        output.WriteInt32(Int);
      }
      if (HasFloat) {
        output.WriteRawTag(85);
        output.WriteFloat(Float);
      }
      if (HasBool) {
        output.WriteRawTag(88);
        output.WriteBool(Bool);
      }
      if (HasStr) {
        output.WriteRawTag(98);
        output.WriteString(Str);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::CompasPb.Data.DataType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (dataCase_ == DataOneofCase.Point) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Point);
      }
      if (dataCase_ == DataOneofCase.Vector) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vector);
      }
      if (dataCase_ == DataOneofCase.Line) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Line);
      }
      if (dataCase_ == DataOneofCase.Frame) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Frame);
      }
      if (dataCase_ == DataOneofCase.Element) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Element);
      }
      if (dataCase_ == DataOneofCase.List) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(List);
      }
      if (dataCase_ == DataOneofCase.Dict) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Dict);
      }
      if (HasInt) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int);
      }
      if (HasFloat) {
        size += 1 + 4;
      }
      if (HasBool) {
        size += 1 + 1;
      }
      if (HasStr) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Str);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnyData other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::CompasPb.Data.DataType.Unknown) {
        Type = other.Type;
      }
      switch (other.DataCase) {
        case DataOneofCase.Point:
          if (Point == null) {
            Point = new global::CompasPb.Data.PointData();
          }
          Point.MergeFrom(other.Point);
          break;
        case DataOneofCase.Vector:
          if (Vector == null) {
            Vector = new global::CompasPb.Data.VectorData();
          }
          Vector.MergeFrom(other.Vector);
          break;
        case DataOneofCase.Line:
          if (Line == null) {
            Line = new global::CompasPb.Data.LineData();
          }
          Line.MergeFrom(other.Line);
          break;
        case DataOneofCase.Frame:
          if (Frame == null) {
            Frame = new global::CompasPb.Data.FrameData();
          }
          Frame.MergeFrom(other.Frame);
          break;
        case DataOneofCase.Element:
          if (Element == null) {
            Element = new global::CompasPb.Data.ElementData();
          }
          Element.MergeFrom(other.Element);
          break;
        case DataOneofCase.List:
          if (List == null) {
            List = new global::CompasPb.Data.ListData();
          }
          List.MergeFrom(other.List);
          break;
        case DataOneofCase.Dict:
          if (Dict == null) {
            Dict = new global::CompasPb.Data.DictData();
          }
          Dict.MergeFrom(other.Dict);
          break;
        case DataOneofCase.Int:
          Int = other.Int;
          break;
        case DataOneofCase.Float:
          Float = other.Float;
          break;
        case DataOneofCase.Bool:
          Bool = other.Bool;
          break;
        case DataOneofCase.Str:
          Str = other.Str;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::CompasPb.Data.DataType) input.ReadEnum();
            break;
          }
          case 18: {
            global::CompasPb.Data.PointData subBuilder = new global::CompasPb.Data.PointData();
            if (dataCase_ == DataOneofCase.Point) {
              subBuilder.MergeFrom(Point);
            }
            input.ReadMessage(subBuilder);
            Point = subBuilder;
            break;
          }
          case 26: {
            global::CompasPb.Data.VectorData subBuilder = new global::CompasPb.Data.VectorData();
            if (dataCase_ == DataOneofCase.Vector) {
              subBuilder.MergeFrom(Vector);
            }
            input.ReadMessage(subBuilder);
            Vector = subBuilder;
            break;
          }
          case 34: {
            global::CompasPb.Data.LineData subBuilder = new global::CompasPb.Data.LineData();
            if (dataCase_ == DataOneofCase.Line) {
              subBuilder.MergeFrom(Line);
            }
            input.ReadMessage(subBuilder);
            Line = subBuilder;
            break;
          }
          case 42: {
            global::CompasPb.Data.FrameData subBuilder = new global::CompasPb.Data.FrameData();
            if (dataCase_ == DataOneofCase.Frame) {
              subBuilder.MergeFrom(Frame);
            }
            input.ReadMessage(subBuilder);
            Frame = subBuilder;
            break;
          }
          case 50: {
            global::CompasPb.Data.ElementData subBuilder = new global::CompasPb.Data.ElementData();
            if (dataCase_ == DataOneofCase.Element) {
              subBuilder.MergeFrom(Element);
            }
            input.ReadMessage(subBuilder);
            Element = subBuilder;
            break;
          }
          case 58: {
            global::CompasPb.Data.ListData subBuilder = new global::CompasPb.Data.ListData();
            if (dataCase_ == DataOneofCase.List) {
              subBuilder.MergeFrom(List);
            }
            input.ReadMessage(subBuilder);
            List = subBuilder;
            break;
          }
          case 66: {
            global::CompasPb.Data.DictData subBuilder = new global::CompasPb.Data.DictData();
            if (dataCase_ == DataOneofCase.Dict) {
              subBuilder.MergeFrom(Dict);
            }
            input.ReadMessage(subBuilder);
            Dict = subBuilder;
            break;
          }
          case 72: {
            Int = input.ReadInt32();
            break;
          }
          case 85: {
            Float = input.ReadFloat();
            break;
          }
          case 88: {
            Bool = input.ReadBool();
            break;
          }
          case 98: {
            Str = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::CompasPb.Data.DataType) input.ReadEnum();
            break;
          }
          case 18: {
            global::CompasPb.Data.PointData subBuilder = new global::CompasPb.Data.PointData();
            if (dataCase_ == DataOneofCase.Point) {
              subBuilder.MergeFrom(Point);
            }
            input.ReadMessage(subBuilder);
            Point = subBuilder;
            break;
          }
          case 26: {
            global::CompasPb.Data.VectorData subBuilder = new global::CompasPb.Data.VectorData();
            if (dataCase_ == DataOneofCase.Vector) {
              subBuilder.MergeFrom(Vector);
            }
            input.ReadMessage(subBuilder);
            Vector = subBuilder;
            break;
          }
          case 34: {
            global::CompasPb.Data.LineData subBuilder = new global::CompasPb.Data.LineData();
            if (dataCase_ == DataOneofCase.Line) {
              subBuilder.MergeFrom(Line);
            }
            input.ReadMessage(subBuilder);
            Line = subBuilder;
            break;
          }
          case 42: {
            global::CompasPb.Data.FrameData subBuilder = new global::CompasPb.Data.FrameData();
            if (dataCase_ == DataOneofCase.Frame) {
              subBuilder.MergeFrom(Frame);
            }
            input.ReadMessage(subBuilder);
            Frame = subBuilder;
            break;
          }
          case 50: {
            global::CompasPb.Data.ElementData subBuilder = new global::CompasPb.Data.ElementData();
            if (dataCase_ == DataOneofCase.Element) {
              subBuilder.MergeFrom(Element);
            }
            input.ReadMessage(subBuilder);
            Element = subBuilder;
            break;
          }
          case 58: {
            global::CompasPb.Data.ListData subBuilder = new global::CompasPb.Data.ListData();
            if (dataCase_ == DataOneofCase.List) {
              subBuilder.MergeFrom(List);
            }
            input.ReadMessage(subBuilder);
            List = subBuilder;
            break;
          }
          case 66: {
            global::CompasPb.Data.DictData subBuilder = new global::CompasPb.Data.DictData();
            if (dataCase_ == DataOneofCase.Dict) {
              subBuilder.MergeFrom(Dict);
            }
            input.ReadMessage(subBuilder);
            Dict = subBuilder;
            break;
          }
          case 72: {
            Int = input.ReadInt32();
            break;
          }
          case 85: {
            Float = input.ReadFloat();
            break;
          }
          case 88: {
            Bool = input.ReadBool();
            break;
          }
          case 98: {
            Str = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///* repeated serves as a list in protobuf 
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ListData : pb::IMessage<ListData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ListData> _parser = new pb::MessageParser<ListData>(() => new ListData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ListData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CompasPb.Data.MessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListData(ListData other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListData Clone() {
      return new ListData(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CompasPb.Data.AnyData> _repeated_data_codec
        = pb::FieldCodec.ForMessage(10, global::CompasPb.Data.AnyData.Parser);
    private readonly pbc::RepeatedField<global::CompasPb.Data.AnyData> data_ = new pbc::RepeatedField<global::CompasPb.Data.AnyData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CompasPb.Data.AnyData> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ListData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ListData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      data_.WriteTo(ref output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ListData other) {
      if (other == null) {
        return;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            data_.AddEntriesFrom(ref input, _repeated_data_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DictData : pb::IMessage<DictData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DictData> _parser = new pb::MessageParser<DictData>(() => new DictData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DictData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CompasPb.Data.MessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DictData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DictData(DictData other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DictData Clone() {
      return new DictData(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pbc::MapField<string, global::CompasPb.Data.AnyData>.Codec _map_data_codec
        = new pbc::MapField<string, global::CompasPb.Data.AnyData>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::CompasPb.Data.AnyData.Parser), 10);
    private readonly pbc::MapField<string, global::CompasPb.Data.AnyData> data_ = new pbc::MapField<string, global::CompasPb.Data.AnyData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::CompasPb.Data.AnyData> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DictData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DictData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Data.Equals(other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      data_.WriteTo(output, _map_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      data_.WriteTo(ref output, _map_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_map_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DictData other) {
      if (other == null) {
        return;
      }
      data_.MergeFrom(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            data_.AddEntriesFrom(input, _map_data_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            data_.AddEntriesFrom(ref input, _map_data_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///* root serialization element 
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MessageData : pb::IMessage<MessageData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageData> _parser = new pb::MessageParser<MessageData>(() => new MessageData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CompasPb.Data.MessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageData(MessageData other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageData Clone() {
      return new MessageData(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::CompasPb.Data.AnyData data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CompasPb.Data.AnyData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageData other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::CompasPb.Data.AnyData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::CompasPb.Data.AnyData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::CompasPb.Data.AnyData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
