# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compas_pb/data/proto/message.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'compas_pb/data/proto/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from compas_pb.data.proto import point_pb2 as compas__pb_dot_data_dot_proto_dot_point__pb2
from compas_pb.data.proto import vector_pb2 as compas__pb_dot_data_dot_proto_dot_vector__pb2
from compas_pb.data.proto import line_pb2 as compas__pb_dot_data_dot_proto_dot_line__pb2
from compas_pb.data.proto import element_pb2 as compas__pb_dot_data_dot_proto_dot_element__pb2
from compas_pb.data.proto import frame_pb2 as compas__pb_dot_data_dot_proto_dot_frame__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"compas_pb/data/proto/message.proto\x12\x0e\x63ompas_pb.data\x1a compas_pb/data/proto/point.proto\x1a!compas_pb/data/proto/vector.proto\x1a\x1f\x63ompas_pb/data/proto/line.proto\x1a\"compas_pb/data/proto/element.proto\x1a compas_pb/data/proto/frame.proto\"\xed\x02\n\x07\x41nyData\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.compas_pb.data.DataType\x12*\n\x05point\x18\x02 \x01(\x0b\x32\x19.compas_pb.data.PointDataH\x00\x12,\n\x06vector\x18\x03 \x01(\x0b\x32\x1a.compas_pb.data.VectorDataH\x00\x12(\n\x04line\x18\x04 \x01(\x0b\x32\x18.compas_pb.data.LineDataH\x00\x12*\n\x05\x66rame\x18\x05 \x01(\x0b\x32\x19.compas_pb.data.FrameDataH\x00\x12.\n\x07\x65lement\x18\x06 \x01(\x0b\x32\x1b.compas_pb.data.ElementDataH\x00\x12(\n\x04list\x18\x07 \x01(\x0b\x32\x18.compas_pb.data.ListDataH\x00\x12(\n\x04\x64ict\x18\x08 \x01(\x0b\x32\x18.compas_pb.data.DictDataH\x00\x42\x06\n\x04\x64\x61ta\"1\n\x08ListData\x12%\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x17.compas_pb.data.AnyData\"\x82\x01\n\x08\x44ictData\x12\x30\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\".compas_pb.data.DictData.DataEntry\x1a\x44\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.compas_pb.data.AnyData:\x02\x38\x01\"4\n\x0bMessageData\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.compas_pb.data.AnyData*d\n\x08\x44\x61taType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05POINT\x10\x01\x12\n\n\x06VECTOR\x10\x02\x12\x08\n\x04LINE\x10\x03\x12\t\n\x05\x46RAME\x10\x04\x12\x0b\n\x07\x45LEMENT\x10\x05\x12\x08\n\x04LIST\x10\x06\x12\x08\n\x04\x44ICT\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compas_pb.data.proto.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DICTDATA_DATAENTRY']._loaded_options = None
  _globals['_DICTDATA_DATAENTRY']._serialized_options = b'8\001'
  _globals['_DATATYPE']._serialized_start=832
  _globals['_DATATYPE']._serialized_end=932
  _globals['_ANYDATA']._serialized_start=227
  _globals['_ANYDATA']._serialized_end=592
  _globals['_LISTDATA']._serialized_start=594
  _globals['_LISTDATA']._serialized_end=643
  _globals['_DICTDATA']._serialized_start=646
  _globals['_DICTDATA']._serialized_end=776
  _globals['_DICTDATA_DATAENTRY']._serialized_start=708
  _globals['_DICTDATA_DATAENTRY']._serialized_end=776
  _globals['_MESSAGEDATA']._serialized_start=778
  _globals['_MESSAGEDATA']._serialized_end=830
# @@protoc_insertion_point(module_scope)
